ALTER TABLE public.quotation_items
  ADD COLUMN IF NOT EXISTS qty2 text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS rate2 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount2 numeric NOT NULL DEFAULT 0;